### ISSUE TITLE
Load Image node - internal error loading rescaled image from Stable Diffusion

### ISSUE THREAD

**Issue by psydrin** [joeyballentine/chaiNNer#1007]
**Information:**
- Chainner version: 0.12.7
- OS: Windows 11

**Description**
After generating an image variation using stable diffusion with the starting image resolution of 2048x2048 then creating an output image that's resized to 512x512, chaiNNer fails to load the resulting image into the load image node with an internal error.

Here are a few example images that fail. They ended up around 10-13.5 MB each so too large to upload here. 
https://drive.google.com/drive/folders/1S7KB0r0Lx-QciODYlcyXcoVAgvva9r9q?usp=sharing

**Logs**
[logs.zip](https://github.com/joeyballentine/chaiNNer/files/9612951/logs.zip)

**Comment by RunDevelopment** [comment]
Can reproduce. For some reason, OpenCV cannot read those PNGs. Will investigate.

Also, why are these PNGs so massive? When I re-save them in Paint.net, they come out as ~0.5MB each. Did you save them as 16bit?

**Comment by 0x4E69676874466F78** [comment]
@RunDevelopment 
![image](https://user-images.githubusercontent.com/4449851/191506276-9b46982e-3465-4951-93ea-d090ff73cc5d.png)
Its sd parameters with base64 img (2048x2048) embedded.
![image](https://user-images.githubusercontent.com/4449851/191507298-70e4bb0e-9e0e-48de-a7bc-6a312e6381d0.png)

**Comment by RunDevelopment** [comment]
Thanks for the info @0x4E69676874466F78!

It seems that OpenCV does not support PNGs with text chunks. Fortunately, PIL does support them, so I already have a workaround (will make a PR shortly). 

However, this is still something that OpenCV should fix. I would to make a bug report to OpenCV. @psydrin, may I use a copy of one of your images as an example of the bug?

**Comment by psydrin** [comment]
Absolutely and thank you both!
