### ISSUE TITLE
Folder iterator missing

### ISSUE THREAD

**Issue by jslegers** [joeyballentine/chaiNNer#1019]
**Motivation**
I've been using a single script to upscale roughly 4000 images I've generated with Stable Diffusion. I'm doing this in one batch that I continue running while I'm sleeping.

While this method does technically work, organising 4000 images in one folder is inefficient, and so is duplicating them there. 

**Description**
I'd like the ability to iterate over different subfolders in my working folder in a single batch run, so I can keep my files nearly structured as I upscale them.

**Alternatives**
Thusfar, I just moved all my images in a single subfolder and named them [letters][1-80] so keep them somewhat organised. This was a very timeconsuming process, however, and not really practical at all. I could, of course, just change my working folder after every run, but this too is inefficient, as this requires a manual check on a regular basis, which I can't do when I sleep or I'm not home.

**Comment by theflyingzamboni** [comment]
The Image Iterator already walks subdirectories as well. If you want to preserve the structure in the output directory, connect Relative Path from the Load Image to the Save Image node.

**Comment by jslegers** [comment]
> The Image Iterator already walks subdirectories as well. 

Right now, my script outputs the upscaled images in a subfolder named "output". Whenever I re-run my script, it completely ignores any content in the "output" subfolder. So, at least with my current script, it seems subfolders are ignored.

Is this a configuration issue? If yes, what do I need to do so sub-folders are no longer ignored?

**Comment by theflyingzamboni** [comment]
Could you share a screenshot of the chain you're currently using?

**Comment by jslegers** [comment]
## Incoming

![afbeelding](https://user-images.githubusercontent.com/883647/191797809-63fe2097-cb66-4a5e-8c5e-dc7e7881e475.png)

## Outgoing

![afbeelding](https://user-images.githubusercontent.com/883647/191798042-c4990475-0107-436a-9361-fbcf01257551.png)

**Comment by joeyballentine** [comment]
You need to connect the "relative path" output from the load image to the save image

**Comment by joeyballentine** [comment]
@theflyingzamboni maybe we should rename that to something more obvious like "subdirectory path"

**Comment by jslegers** [comment]
> You need to connect the "relative path" output from the load image to the save image

And then my subdirectories will no longer be ignored?

> @theflyingzamboni maybe we should rename that to something more obvious like "subdirectory path"

That would definitely be more useful.

I only just noticed that you actually have a similar use case in your examples list. I guess I should just copy the connection scheme from this template to fix my issue?

![afbeelding](https://user-images.githubusercontent.com/883647/191803982-c7d3f6cb-680b-476f-9111-27ea85b7c7b9.png)

**Comment by joeyballentine** [comment]
Yes. Then the subdirectories will no longer be ignored

**Comment by theflyingzamboni** [comment]
![image](https://user-images.githubusercontent.com/55669985/191811233-4dc7f7e7-34df-479c-87b9-389941f8bf06.png)
This specifically is the connection I mentioned above that preserves subdirectory structure.

**Comment by jslegers** [comment]
Before I again open a ticket for a feature that already exists...

Is there a way to run chaiNNer scripts in background from a console / shell script? This would be very convenient eg. for backends of web apps.

**Comment by RunDevelopment** [comment]
> Is there a way to run chaiNNer scripts in background from a console / shell script?

Not yet. I don't think we have an issue for that yet, but you also don't need to open one. I plan to implement this in the next couple of days.

**Comment by jslegers** [comment]
> Not yet. I don't think we have an issue for that yet, but you also don't need to open one. I plan to implement this in the next couple of days.

That would be so awesome!!

Along with support for other model types (especially GFPGAN & Stable Diffusion, ...), that would be the feature I'm looking forward to the most!!

**Comment by theflyingzamboni** [comment]
> Along with support for other model types (especially GFPGAN & Stable Diffusion), that would be the feature I'm looking forward to the most!!

Won't have to wait long for GFPGAN, it's already implemented in dev and will be in the next major release.
