### ISSUE TITLE
Merge Load Image and Iterator Nodes

### ISSUE THREAD

**Issue by octopushugger** [joeyballentine/chaiNNer#120]
As it is currently it appears you have to create your chain twice if you want to use it on a specific image and then decide to run a batch. Would be more intuitive and less work to have the iterator node removed and its functions integrated into the regular load image node for when you have a folder selected instead of a single image. 
Or if it's less work to program just make the iterator node compatible with existing nodes instead of forcing it into its own empty window. 

While I'm already posting I would like to add that implementing file drag&drop functionality to the load image and load model nodes would also be very useful.

**Comment by joeyballentine** [comment]
I plan on adding a feature to iterators where you can import an existing .chn file into them and it will load all the nodes in, to alleviate this problem. 

At some point I'll probably also make it possible to drag existing nodes into the iterator editor, as well as allowing copy and pasting in. But that's a bit more complicated.

That being said, I'm definitely not going to just make the load image node an iterator, that makes no sense. But I do agree it's a bit convoluted at the moment.

**Comment by theflyingzamboni** [comment]
To expand on the difficulties of not having an explicit iterator "environment," consider a situation where you want to apply a specific mask to everything in a folder for whatever reason. You want to iterate through the directory, but you only want the mask to load one time. Having an explicitly defined iterator environment makes this a) easier to accomplish from the backend, and b) more obvious to the user what they are doing. I agree with Joey that simply making it easy to move things in and out of and iterator is likely a better solution.

**Comment by joeyballentine** [comment]
This will be fixed in the future when iterators are rewritten.
