### ISSUE TITLE
[Suggestion] Package App for Linux as .AppImage

### ISSUE THREAD

**Issue by alsa64** [joeyballentine/chaiNNer#13]
AppImages run on all major Distributions, are portable, preventing QA issues from having different versions of Libraries on different systems.

You could drop .deb and .rpm support for it too, hopefully shortening your build times.

Some Relevant links:

- [npmjs - AppImage - Electron Forge](https://www.npmjs.com/package/electron-forge-maker-appimage)
- [appimage.org Electron Builder](https://appimage.org/
https://www.electron.build/configuration/appimage.html)

**Comment by joeyballentine** [comment]
Closing this because the linked electron forge thing wants me to use electron builder to do it otherwise it will break my github action.

Also, the zip build should be good enough because it also should run on all distros and is portable, so in my mind appimage is redundant.

**Comment by RossSmyth** [comment]
The zip build does not work on all linux distro as it assumes things about the file system layout, which mainly means it does not work on NixOS without some effort. AppImage does just work and it would be nice if it was used.
