### ISSUE TITLE
[ Question ] Where are dependencies installed in a portable install?

### ISSUE THREAD

**Issue by iwubcode** [joeyballentine/chaiNNer#237]
I chose to install with the portable install of chainner.  I had hoped all dependencies would be installed under that portable folder but it doesn't seem to be the case (or I'm missing them).

Can someone confirm where those dependencies are?  I know I can uninstall from the managed dependencies folder for some apps but python (integrated) cannot and I was curious where that was (I swear I alread had python installed).

**Comment by joeyballentine** [comment]
It is located in your appdata folder, in the python folder

**Comment by iwubcode** [comment]
Thank you very much.  I see python and ncnn now!

**Comment by joeyballentine** [comment]
For anyone that might be seeing this in the future I should have been a bit more specific. It's located in appdata > chaiNNer > python
