### ISSUE TITLE
[ Feature ] Image comparison node

### ISSUE THREAD

**Issue by iwubcode** [joeyballentine/chaiNNer#240]
Likely a follow up to #220 that used similar tech, would be some sort of comparison node with the ability to compare side-by-side, animate between two images, or even a slider.

**Comment by joeyballentine** [comment]
To compare side by side right now, use the image stack node

**Comment by theflyingzamboni** [comment]
@joeyballentine This issue should be closed, as it is already part of the preview node issue (as well as the stack node providing the other part of this functionality).

**Comment by iwubcode** [comment]
Stack node works for now, didn't think of using it in that way.  It would be nice to support an animation or a slider based approach as well though.
