### ISSUE TITLE
"Discard changes?" dialog on open should come before the open file dialog

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#339]
It's strange that the open file dialog shows up, the user selects a file, and then we essentially ask: "Are you sure that you *really* want to open that file?"

**Comment by joeyballentine** [comment]
I was about to implement this, then I realized that would require back and forth IPC which is kinda gross, and then also it would not match the behavior of open recent, which would be unable to be done the way you suggest. I'd rather have them match.

**Comment by joeyballentine** [comment]
Another nail in the coffin, open and then ask for discard is what other programs do as well
