### ISSUE TITLE
[ Question ] Why is pytorch now needed?

### ISSUE THREAD

**Issue by iwubcode** [joeyballentine/chaiNNer#393]
I have an AMD GPU and just installed the latest update.  Unfortunately I have no nodes available.  Looking at my missing dependencies "Pillow" and "pyTorch" weren't installed.  Why is pytorch needed if I'm using NCNN for my upscales?

**Comment by joeyballentine** [comment]
This is probably due to an issue that was recently fixed but not released where there was some code not getting safely imported, which causes the backend to not load properly when those packages are not installed. This will be fixed in the next release.

**Comment by theflyingzamboni** [comment]
@joeyballentine Was this fixed on 0.9.0?

**Comment by joeyballentine** [comment]
Yes
