### ISSUE TITLE
[ Question ] Why is directory iterator a separate area?

### ISSUE THREAD

**Issue by iwubcode** [joeyballentine/chaiNNer#395]
I built up a workflow then setup a directory iterator, only to find I couldn't link my previous flow to the directory iterator.  I'm assuming this is because those nodes weren't "inside" the directory iterator.  Is that true?  If so, why the separate approach for this node?

**Comment by joeyballentine** [comment]
This is a known pain point of chaiNNer. I hope to allow the ability to drag and drop, as well as copy and paste, existing nodes into iterators at some point. Also, the way iterators work will be changed in the future as well, so eventually this won't be an issue at all.
