### ISSUE TITLE
[Bug] 'optional' flag in Text Append node doesn't work

### ISSUE THREAD

**Issue by TheIceCreamTroll** [joeyballentine/chaiNNer#40]
~~Currently, every field in the Text Append node has to have something entered in order for the flowchart to run, which can be an issue when you only have two text inputs you want to append. Ideally, they should be able to be left blank.~~

Edit: Looks like this is actually implemented in ```utility_nodes.py```, but it doesn't seem to be working as intended.

**Comment by joeyballentine** [comment]
Just recreated it. It works properly when you connect text from another node to it, but not when entering the text manually. Will look into it.
