### ISSUE TITLE
Add "All files (*.*)" filter to the Open Image dialog

### ISSUE THREAD

**Issue by Unordinal** [joeyballentine/chaiNNer#408]
The dialog used when opening an image file has a filter with a long list of image formats. However, there are sometimes files with different or even no extensions that are, in actuality, a supported format that cannot be selected because of the specific filter without renaming every file you want to use. An "All files (\*.\*)" filter that the user could select for these cases would be extremely welcome.

In my case I have hundreds of TIFF files that have the extension ".tif" when only ".tiff" is listed in the filter, making them unavailable. For my specific case simply adding ".tif" to the filter would do fine (as seems to have been done for ".jpg", ".jpeg", etc for instance) but there's bound to be more examples where simply being able to select a file with any extension would be useful.

**Comment by joeyballentine** [comment]
The main reason for not doing this was to help prevent unsupported files from being selected, but we could add this and just do some more validation after selecting the file instead.
