### ISSUE TITLE
Rotate should allow arbitrary rotation amount

### ISSUE THREAD

**Issue by theflyingzamboni** [joeyballentine/chaiNNer#415]
Currently, the rotate node has a drop down that only allows 90 degree rotation increments. This should be a number input that accepts decimals 0≤d<360.

**Comment by joeyballentine** [comment]
> Currently, the rotate node has a drop down that only allows 90 degree rotation increments. This should be a number input that accepts decimals 0≤d<360.

It was done this way because this is how cv2's rotate function works. If you'd like to implement a rotation algorithm yourself, feel free.

**Comment by joeyballentine** [comment]
Actually, PIL's rotate accepts an arbitrary value, so we could just use that www.geeksforgeeks.org/python-pil-paste-and-rotate-method/

**Comment by theflyingzamboni** [comment]
@joeyballentine PIL is what I've used for it.

**Comment by theflyingzamboni** [comment]
@RunDevelopment
1) It would expand to fit the new dimensions. If we want image expansion to be optional, that is an argument for PIL's rotate, and we can just have a dropdown for it.
2) Channel count does not change. PIL rotate also has a fill argument. Right now, I just have it as black when there is no alpha channel. Would be nice to have that changeable (same goes for the border node), but we'd need a color picker for that. Could also make solid vs transparent fill an option, so the user could choose whether the channels expand.
