### ISSUE TITLE
invalid opcode in libtorch_cuda_cpp.so

### ISSUE THREAD

**Issue by itewreed** [joeyballentine/chaiNNer#43]
When I try to do an image upscale the upscaling fails and I see the following two things in the logfiles
```
Python subprocess exited with code null and signal SIGILL
kernel: [ 7750.737022] traps: python[176224] trap invalid opcode ip:7febea60213e sp:7feb82c920d0 error:0 in libtorch_cuda_cpp.so[7febe27a0000+61c96000]
```

So this seems to has something to do with my graphic card, which is a RTX3060, 12GB, because using CPU instead of GPU works.

I'm running this under Kubuntu 21.10.
Driver info: Driver Version: 470.103.01   CUDA Version: 11.4

If this is not directly related to chaiNNer, can you please add Information to the documentation, e.g. how to make pytorch to work with these Graphiccards?

I used the latest chaiNNer 0.4.3

**Comment by joeyballentine** [comment]
I haven't seen an error like this before, but the first thing I would try is updating your drivers. 470 is a bit old, and might cause issues with newer pytorch builds. If that doesn't work, please let me know. I think pytorch changed something with their install command so it could also be something related to that, but you should start with a driver update.

**Comment by itewreed** [comment]
I tested it now on another system and there it runs without error. Specs are
Ubuntu 20.04 LTS, Kernel 5.13.0-30-generic
Driver Version: 470.103.01   CUDA Version: 11.4
NVIDIA GeForce GTX 1660, 6GB

However, the CPU on the system where the opcode error appears is very old. I should give it also a try to put the 3060 into the system which currently holds the 1060.

**Comment by itewreed** [comment]
I'll close this, as it probably has to do with a very outdated CPU.
