### ISSUE TITLE
[Bug] [macOS/aarch64] [frontend] Dragging and Dropping Nodes doesn't work.

### ISSUE THREAD

**Issue by alsa64** [joeyballentine/chaiNNer#5]
If I drag a node from the selection panel and drop it onto the canvas, it doesn't appear on the canvas.

I am running on a MacBook Air from 2020 (M1 / Apple aarch64, through Rosetta)

[Video Recording](https://cdn.discordapp.com/attachments/916354036305887272/927820350463569960/Screen_Recording_2022-01-04_at_08.05.27.mov)

**Comment by joeyballentine** [comment]
This is fixed now
