### ISSUE TITLE
Custom nodes?

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#53]
Is/will there be support for custom nodes? 

I have a few things that I need chainner to support for it to be useful to me. I've already implemented these feature in a C# project of mine, but I can easily port them to any language.

**Comment by joeyballentine** [comment]
You could always fork the repo and implement anything custom you need yourself. Implementing something to allow any arbitrary code to run would be interesting, but I'm not entirely sure how that would work. It would be much easier, at least for the time being, for you to just implement stuff in a separate fork, and if you think those things would be useful to others then make a PR.
