### ISSUE TITLE
Disabled nodes are animated as running

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#539]
When you run a chain with disabled nodes, those nodes will be animated as running. Since they never actually run, we never get "node finished" message from the backend, so these nodes get animated as running until the whole chain finishes (or aborts).

![image](https://user-images.githubusercontent.com/20878432/178533281-85c6357c-b5a5-415f-9948-194247affcb5.png)

**Comment by RunDevelopment** [comment]
The problem is actually even more general. The executor will only run nodes required for nodes with side effects. So if a node does not have a side effect downstream node, then it will have the same problem.

**Comment by joeyballentine** [comment]
I was going to say we could just make it not do the animation if its disabled (we should probably still do that), but the more general problem I'm not sure how to solve. I suppose we would have to check on every node if it has a child that has side effects?
