### ISSUE TITLE
Don't save empty views

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#56]
I have found a bug where saving a workflow will just write an empty workflow to disk:

```json
{"version":"0.5.2","content":{"nodes":[],"edges":[],"viewport":{"x":0,"y":0,"zoom":1}},"timestamp":"2022-04-27T17:36:16.425Z"}
```

I'm still trying to reproduce that bug and will make a separate issue for it. 

In the meantime, please add a warning or make it impossible to save empty workflows. Saving empty workflows has no value anyway and would have made it easier to detect this bug.

---

Also, why is the JSON base64 encoded? Why not just save plain JSON and make the `.cha` files easy to debug?

**Comment by joeyballentine** [comment]
I'll add this to the list of stuff I need to do for saving. There's a lot of quality of life things I need to add. For example, it won't alert you when you have unsaved changes. 

Also I base64 encoded it so people wouldn't just see that it's JSON and try to change around stuff. I can see potential cases happening where people just edit their .chn files manually and complain that chaiNNer broke, so I wanted to obscure it a bit to prevent that (unless you know what you're doing of course)

**Comment by RunDevelopment** [comment]
> I can see potential cases happening where people just edit their .chn files manually and complain that chaiNNer broke

That's valid, but if that is the only reason to obfuscate the JSON, then wouldn't a checksum of sorts be better? Kinda like this:

```json
{
  "data": {...},
  "checksum": "md5 or whatnot of data"
}
```

Now we could show a warning saying that stuff has been tampered with.

**Comment by joeyballentine** [comment]
That's a very good way of doing that and I'm definitely down to change it to that.
