### ISSUE TITLE
Saving does not work correctly

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#57]
When saving a new workflow via Ctrl+S, the workflow won't be saved.

Steps to reproduce:
1. Make a new workflow
2. Add some nodes
3. Ctrl+S
4. Choose a file name and save
5. Open the saved file
6. All nodes will now be gone

This is because the saved file does not contain any information about the nodes. Example:

```json
{"version":"0.5.2","content":{"nodes":[],"edges":[],"viewport":{"x":305.96171293776086,"y":-174.04899292324444,"zoom":0.5244057339865723}},"timestamp":"2022-04-27T17:50:34.429Z"}
```

**Comment by joeyballentine** [comment]
@

**Comment by joeyballentine** [comment]
(oops, didn't mean to close this)

Nice catch. Guess I haven't tested that in a while
