### ISSUE TITLE
Sidebar / Node-bar code and usage in external projects

### ISSUE THREAD

**Issue by D-Niermann** [joeyballentine/chaiNNer#578]
Hello Joeyballentine,

I came across your project from the react-flow website and it looks amazing!

My Background: 
I am currently also using react-flow within a German research project named KoMILo to build a software for robot control. You can see more about the project at www.comflow-project.de. Of course we work non-profit and publish scientific papers about our research. 

My Question: 
Can we use your sidebar in our software framework? If yes, it would be nice if we could go into direct contact (per Mail or possibly even Skype / Discord or similar) so that you can show me what exactly we need to implement. 

Feel free to answer me here or at nie@biba.uni-bremen.de

Thank you and Kind Regards,
D-Niermann

**Comment by joeyballentine** [comment]
Hello,

As you're probably aware, this project is GPLv3 licensed (which I'm sure is why you've reached out directly) so copying it directly might not what you're looking for. 

As for how to implement it yourself, all it really is in chaiNNer is a modification of this basic drag and drop example from react flow: https://reactflow.dev/docs/examples/interaction/drag-and-drop/

Essentially I just have my list of nodes, make them draggable via the HTML drag and drop API, and add a new node at the dropped position using react flow's onDrop callback. It's actually extremely similar to that example and hasn't changed much.

If you'd like to further reach out to me, you can contact me on Discord, username Joey#4305

**Comment by D-Niermann** [comment]
Hi Joey,

thank you for contacting me back!
I sent you a Discord invite (From my account with the name StierHoden).  

Best regards,
Dario
