### ISSUE TITLE
ChaiNNer loses name of current file on reload

### ISSUE THREAD

**Issue by theflyingzamboni** [joeyballentine/chaiNNer#586]
~If you hit a runtime error while running a chain in a chain that you have already saved, the filename in the header will revert to unnamed and Save will require you to Save As, because the association between the chain and the file gets broken.~

Using View -> Reload causes chain to lose association to its filename, the header reverts to "Untitled", and Save As is required to save chain again.

**Comment by RunDevelopment** [comment]
Do you mean a runtime error in the backend or the frontend?

**Comment by theflyingzamboni** [comment]
Rechecking the issue, it's actually the reloading causing the issue, something I tend to do when I hit errors in testing. Updated issue accordingly.
