### ISSUE TITLE
[Bug] [Windows/x86_64] [frontend] Application remains frozen when opened

### ISSUE THREAD

**Issue by alsa64** [joeyballentine/chaiNNer#6]
If I open chaiNNer on Windows, it will remain frozen until I either:
- Focus and unfocus the window
- Click anywhere else

**Comment by joeyballentine** [comment]
I haven't had this happen to me in a long time, so I'm going to assume this is fixed. If it isn't, I don't even know what I can do to fix it... But if so I can reopen this
