### ISSUE TITLE
Input type tags

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#605]
Right now, inputs only have an "optional" tag (if optional), but know a lot more about inputs. It would be nice to have some for of input type tags.

**Comment by joeyballentine** [comment]
For this, would it be possible to replace the current way that the optional tag is done, and just make optional part of the type tags?

**Comment by joeyballentine** [comment]
I think they should represent any sort of type restrictions rather than the actual type (they can change once connected). For example the merge channels being restricted to gray or some other node having a restricted size

**Comment by RunDevelopment** [comment]
That won't be easy. Input types (restrictions) can depend on each other. E.g. the restriction of the input of the Change Colorspace depend on the current conversion.

I'll have to think about how we should determine the restrictions to display.
