### ISSUE TITLE
Enabling "Snap to grid" on an existing chain causes node misalignment

### ISSUE THREAD

**Issue by kimberly990** [joeyballentine/chaiNNer#662]
If you enable "Snap to grid" on an existing chain with nodes already placed, the nodes will not be aligned. They will "snap" but remain out of the correct positions.

**Comment by joeyballentine** [comment]
So you want them to snap not aligned to the grid?

**Comment by kimberly990** [comment]
No, that's the problem. It's not actually aligned to the grid in this case, it's based on where the node was previously rather than a set "grid" pattern. I'll try to get an example

**Comment by kimberly990** [comment]
This is actually no longer an issue, my bad. It must have been resolved in the last couple of releases
