### ISSUE TITLE
Clicking the nodes tab causes a visual bug

### ISSUE THREAD

**Issue by kimberly990** [joeyballentine/chaiNNer#667]
![image](https://user-images.githubusercontent.com/62084776/182002360-989fd9a5-aa2c-455f-8f47-c106681e5b24.png)

Clicking the nodes tab causes a visual bug

**Comment by RunDevelopment** [comment]
What exactly is the visual bug here? That the focus rectangle is visible or that it is only partially visible?

**Comment by joeyballentine** [comment]
> What exactly is the visual bug here? That the focus rectangle is visible or that it is only partially visible?

It's the overflow: hidden causing the rest of the outline to not show up
