### ISSUE TITLE
Add an "Invert Color" node

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#684]
As per [this message](https://discord.com/channels/930865462852591648/930865463318179952/1004114756090740766).

Given a grayscale or RGB image, the node should return `1-image`.

Not sure how RGBA should be handled. Only inverting RGB while leaving alpha untouched feels natural, but I'm not sure whether it's "correct."

**Comment by joeyballentine** [comment]
I think leaving alpha untouched would be the way to do it. Feels like that's what happens in other image editors
