### ISSUE TITLE
Add a "Copy to Clipboard" node

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#687]
When I edit images, it's sometimes easier to do certain tasks in chainner. E.g. tiling a texture to a certain size. To get the final image into my image editing software, I use the View Image (External) node and then copy the opened image to paste into a new layer in the image I'm working on.

It would be nice to have a node that copies an image to clipboard to speed up my workflow.

**Comment by joeyballentine** [comment]
I think this should be possible by having an image clipboard output, and using a full image broadcast where instead of a preview it gets copied to clipboard. That is, unless python supports copying to clipboard as well

**Comment by RunDevelopment** [comment]
I'd rather not send a 100MB PNG via JSON to the frontend just to write it to the clipboard. This is something the backend has to do.

**Comment by joeyballentine** [comment]
Yeah, I just didn't know if python could copy to clipboard. Since it can, we definitely should do it through that

**Comment by RunDevelopment** [comment]
This has been solved by #920.
