### ISSUE TITLE
Note loads endlessly?

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#691]
When adding a Note node, the node will be animated as loading, when that's not actually the case. Since #680, the `node-finish` event now un-animates nodes, and since Note doesn't have any outputs, that event is never sent.

While this is a bug, I'm not sure which part is wrong. Is it Note being run in the first place (so the heuristic for which nodes to run needs to be changed), or `node-finish` only being sent for nodes with outputs, or both?

![image](https://user-images.githubusercontent.com/20878432/182558269-f1b6ce8e-57ef-476b-800c-d680df2e7633.png)

**Comment by joeyballentine** [comment]
Node finish is only sent for nodes with outputs yes. This node shouldn't be running in the first place though
