### ISSUE TITLE
Add warning when modifying a currently running/paused chain

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#698]
What the title says. Users can edit chains while they are running or being paused. This potentially created multiple issues in the frontend code (all of these are bugs), but the main problem is that the user might get confused, as they might expect edits to parts that have yet to execute to be reflected in the final result.

**Comment by joeyballentine** [comment]
How do we think this should be implemented? I'm thinking just a little floating warning box at the top of the editor pane

**Comment by RunDevelopment** [comment]
Agreed. That's what VS does as well.

**Comment by pokepress** [comment]
Looks like this feature was added in the recent update, however, I noticed a bug. When a pytorch model is used in an image iterator, it looks like the model information redisplays each time an image is processed. Not only does this cause the box for the "Load model" task to change size, but it also triggers a "modification" warning. This could also suggest a performance optimization if we really are reloading the model each time.

**Comment by joeyballentine** [comment]
@pokepress you are supposed to have the load image node outside of the iterator. Yes, it is a performance concern, and yes it is not intuitive. This is one of the reasons we want to change how iterators work.

However, there definitely is some sort of bug, as it does think that something is being changed under that scenario, even though nothing actually is. I am actively looking into it.

**Comment by joeyballentine** [comment]
Closing this as it was added in v0.12
