### ISSUE TITLE
Execution status is not correctly updated

### ISSUE THREAD

**Issue by RunDevelopment** [joeyballentine/chaiNNer#700]
I just experienced a bug where the execution status is not set to `READY` after the chain finished. The chain did not error and doesn't seem to be running in the backend anymore. The logs also don't show anything outside the ordinary.

Killing the chain caused a "Backend: [9808] [INFO] No executor to kill", so the chain really was not running anymore.

**Comment by joeyballentine** [comment]
I wonder if that's caused by us removing unanimate from the SSE handler dep array. Probably same reason as before

**Comment by RunDevelopment** [comment]
Yup. That's it. I'll make a PR.
