### ISSUE TITLE
Any possibility of GFPGAN model support?

### ISSUE THREAD

**Issue by TheEnhas** [joeyballentine/chaiNNer#739]
I use the online versions of it but they tend to go down at times (and in the case of the colab, no longer works at all), so I'd like an (easy) way to use it locally.

**Comment by joeyballentine** [comment]
I've considered it before. It just requires facial detection and cropping and I wasn't sure the best way to accomplish that. But I think if we just had a "upscale faces" node or something like that it could work pretty easily. I'll look into it

**Comment by TheEnhas** [comment]
Thanks for replying, it's just that it works a lot better than most face/people upscalers for me. In particular it does eye restoration very well.

**Comment by joeyballentine** [comment]
Yeah, I've used it before and it works extremely well. It just does more stuff than a normal upscale does so it isn't as simple as just plopping it in like I would anything else
