### ISSUE TITLE
Do not remove the old image in view image until the new is not ready

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#773]
And remove spinner on image block (the spinner is already at the bottom of the node).
![изображение](https://user-images.githubusercontent.com/4449851/185718669-99b9f98c-102b-460a-97a2-5ad94549dc51.png)

Very cool app, thanks!

**Comment by RunDevelopment** [comment]
@joeyballentine Is there a reason why we don't show the old image output? I mean, we have it, we just don't show it. We even have a reliable system to know whether an image output is stale your not.

**Comment by joeyballentine** [comment]
@RunDevelopment because I did the animation thing before the stale indicator thing was there. IMO we really only need to do the animation when there isn't a preview there yet
