### ISSUE TITLE
Model iterator for compare 

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#775]
**Motivation**
It would be nice to set a list of models (for example, open a folder or select files) and then specify folder where to save their upscaling result. File name format: `${imagename}_${modelname}.png`

**Comment by MaKiPL** [comment]
+1 for this. Right now I have to either copy and paste the load model + upscale nodes or click them one-by-one

**Comment by joeyballentine** [comment]
I'm planning on implementing this later today.

**Comment by joeyballentine** [comment]
Closing this as it was added in v0.12

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine if you write `fix #775` in the commit description, then the issue will automatically close when you merge in default branch.

**Comment by joeyballentine** [comment]
@0x4E69676874466F78 I did do that, it just didn't work for some reason. It happened to another issue as well.
![image](https://user-images.githubusercontent.com/34788790/189502090-181024f2-ed56-44fa-b134-9511fbf07ab0.png)
