### ISSUE TITLE
Alpha 0.11.2 on MacOS 11.6

### ISSUE THREAD

**Issue by dem10com** [joeyballentine/chaiNNer#778]
Hi there,

I wanted to try the new version (0.11.2)  on my mac (intel, macos 11.6). After downloading, I am getting the errors I sent in the attachment. Is there anyone have an idea?

Thanks a lot.

![Screen Shot 2022-08-20 at 11 59 08](https://user-images.githubusercontent.com/111634201/185737630-a72cffeb-807b-4b35-bb23-247fa28e94ad.png)
![Screen Shot 2022-08-20 at 11 59 14](https://user-images.githubusercontent.com/111634201/185737643-82ca3c86-0f8a-4cd4-828f-240624834621.png)
a

**Comment by joeyballentine** [comment]
Hi. For clarification, older versions of chaiNNer worked for you previously?

**Comment by dem10com** [comment]
I just tried the previous version and it didn't work either. same error

**Comment by joeyballentine** [comment]
@dem10com I believe this means it was not able to download the python backend it needs. Do you have strict firewall settings or something?

**Comment by dem10com** [comment]
I do not use any firewalls or restrictions. I also tried new version (0.11.3), I didn't get the errors I got before, but this time, the error comes as follows. 

thank you 

![Screen Shot 2022-08-21 at 12 14 14](https://user-images.githubusercontent.com/111634201/185784230-147e3169-8837-4a2f-b2c0-f08d0d5247f9.png)
.

**Comment by dem10com** [comment]
After getting the error  I restarted it and this time it worked. thank you

**Comment by dem10com** [comment]
I even noticed my Macos sees my gpu ( Radeon 5700 xt)  . The windows part I used in the same hardware (hackintosh)  did not detected it.
