### ISSUE TITLE
Rename banner.png to logo.png (or any other name)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#792]
Image https://raw.githubusercontent.com/joeyballentine/chaiNNer/main/src/public/banner.png was blocked by one of the ublock origin default filters.
![изображение](https://user-images.githubusercontent.com/4449851/185755966-531021be-4bcf-47ed-8299-8cc7c6218bcd.png)

<details><summary>What does it look like...</summary>
<p>

![изображение](https://user-images.githubusercontent.com/4449851/185755997-fa2da4a3-4ea1-428d-98d2-8a7304943398.png)

</p>
</details>

**Comment by 0x4E69676874466F78** [comment]
I'll close this issue as it's an ad blocker list issue.

**Comment by RunDevelopment** [comment]
I'd recommend turning off ubo for GitHub in general.

**Comment by 0x4E69676874466F78** [comment]
@RunDevelopment yes but I'm far from the only one who didn't turn it off here.
This creates the appearance of an error in the repo.
I created an issue for the ad block list, let them get better.

**Comment by theflyingzamboni** [comment]
I use uBO as well with whatever the default list is, and it doesn't block it for me.

**Comment by 0x4E69676874466F78** [comment]
@theflyingzamboni because the mistake is only (from confirmed) in the RU AdList.

**Comment by 0x4E69676874466F78** [comment]
Fixed https://github.com/easylist/ruadlist/commit/60efd616a549b4988a70ca745d6ecc87204b48d9
