### ISSUE TITLE
CHAINNER did not recognize my GPU

### ISSUE THREAD

**Issue by evaVSP** [joeyballentine/chaiNNer#794]
**Information:**
- Chainner version: [e.g. 0.11.2]
- OS: [e.g. Windows 10]

**Description**
CHAINNER did not recognize my GPU + it only uses CPU
![image](https://user-images.githubusercontent.com/111653830/185758452-8dc7f563-6da7-4186-9ed3-6f04ed1c47e0.png)
![image](https://user-images.githubusercontent.com/111653830/185758531-b5492996-2a21-48d8-a992-239d4e7aa3a9.png)

**Logs**
[logs.zip](https://github.com/joeyballentine/chaiNNer/files/9387739/logs.zip)
thanks

**Comment by theflyingzamboni** [comment]
What GPU do you have?

**Comment by evaVSP** [comment]
> What GPU do you have?
RTX 2070

**Comment by joeyballentine** [comment]
Does anything come up if you type `nvidia-smi` into the terminal?

**Comment by evaVSP** [comment]
> Does anything come up if you type `nvidia-smi` into the terminal?

yeah 
![image](https://user-images.githubusercontent.com/111653830/185759221-7028ba08-77a1-4662-82fe-c6096e5ea0b1.png)

**Comment by joeyballentine** [comment]
Huh that's weird then

**Comment by joeyballentine** [comment]
Looking at the logs I dont see anything that could indicate that there was an error. This is very strange

**Comment by evaVSP** [comment]
> Looking at the logs I dont see anything that could indicate that there was an error. This is very strange
I got to work, I just added windows\system32 to the path in user & system variables :) and sorry for wasting your time

**Comment by joeyballentine** [comment]
Oh ok, glad you got it to work. Don't forget to reinstall pytorch if you installed it when it didn't recognize your GPU. Otherwise it will still be using CPU.
