### ISSUE TITLE
Error report for chaiNNer 0.11.3

### ISSUE THREAD

**Issue by aft** [joeyballentine/chaiNNer#801]
During launch:

Error:
```UnhandledRejection TypeError: Object has been destroyed
    at n.loadURL (node:electron/js2c/browser_init:33:1843)
    at /Applications/chaiNNer.app/Contents/Resources/app/.webpack/main/index.js:2:77327
    at runNextTicks (node:internal/process/task_queues:61:5)
    at process.processTimers (node:internal/timers:499:9)
```
OS: macOS 10.15

**Comment by joeyballentine** [comment]
@aft would you mind sending a screenshot of the full error message that pops up for this? Thanks

**Comment by aft** [comment]
sure. let me know if you need any other info.
<img width="532" alt="Screen Shot 2022-08-21 at 12 26 38" src="https://user-images.githubusercontent.com/149634/185784662-04b80413-33ff-41a1-837f-56c34abe1b9f.png">
<img width="423" alt="Screen Shot 2022-08-21 at 12 26 31" src="https://user-images.githubusercontent.com/149634/185784665-1a97f881-1024-484d-8fed-1e8c298c8472.png">

**Comment by aft** [comment]
i have also tried previous versions back to x.10 and same problem occurs. here is a log I found:
[main.log](https://github.com/joeyballentine/chaiNNer/files/9388795/main.log)

**Comment by joeyballentine** [comment]
Yeah, looks like it's erroring on the python download. I'll check exactly what it's doing at the line it says though. Will look into it

**Comment by aft** [comment]
Workaround for this issue:

1. Download and install python 3.9 from python.org
2. Make a folder named "python" under ~/Library/Application Support/chaiNNer/python
3. Copy everything in /Library/Frameworks/Python.framework/Versions/3.9 into the newly created folder (~/Library/Application Support/chaiNNer/python/python) - Probably not all the files are needed but doesn't hurt.
4. Launch the app

If it doesn't work, open Terminal and run this command:
`
pip3 install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.5.5.64 numpy==1.22.3 Pillow==9.1.0 --disable-pip-version-check
`

Launch the app.

**Comment by dem10com** [comment]
In the other version ( Macos 10.13.6 High Sierra )  that I did not run, this method worked

tesekkurler Cem


> Workaround for this issue:
> 
> 1. Download and install python 3.9 from python.org
> 2. Make a folder named "python" under ~/Library/Application Support/chaiNNer/python
> 3. Copy everything in /Library/Frameworks/Python.framework/Versions/3.9 into the newly created folder (~/Library/Application Support/chaiNNer/python/python) - Probably not all the files are needed but doesn't hurt.
> 4. Launch the app
> 
> If it doesn't work, open Terminal and run this command: `pip3 install --upgrade sanic==21.9.3 Sanic-Cors==1.0.1 opencv-python==4.5.5.64 numpy==1.22.3 Pillow==9.1.0 --disable-pip-version-check`
> 
> Launch the app.
