### ISSUE TITLE
0.11.3 MacOs 11.6

### ISSUE THREAD

**Issue by dem10com** [joeyballentine/chaiNNer#802]
It doesn't show up even though I downloaded the NCNN package . I reinstalled and restarted but the problem persists

Thank you again

![Screen Shot 2022-08-21 at 12 50 58](https://user-images.githubusercontent.com/111634201/185785609-af58843b-1d71-4e8e-8fcf-b2f340bb8238.png)
![Screen Shot 2022-08-21 at 12 53 24](https://user-images.githubusercontent.com/111634201/185785611-d5798445-5ddd-4f9d-ab72-8a04c550ad8c.png)
.

**Comment by dem10com** [comment]
by the way i dont have m1. I use intel

**Comment by joeyballentine** [comment]
Can you send your logs? They should be somewhere in the application support folder for chaiNNer.

**Comment by aft** [comment]
Location for logs is ~/Library/Logs/chaiNNer/main.log on osx.

**Comment by dem10com** [comment]
here is my log file; i also test on my other mac ( 1080ti + macos 10.13.6, intel ). it didn't work either. 

[main.log](https://github.com/joeyballentine/chaiNNer/files/9389117/main.log)

**Comment by joeyballentine** [comment]
```2022-08-21 15:39:57.735] [error] Backend: dlopen(/Users/demon/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/ncnn_vulkan/ncnn.cpython-39-darwin.so, 2): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/demon/Library/Application Support/chaiNNer/python/python/lib/python3.9/site-packages/ncnn_vulkan/ncnn.cpython-39-darwin.so
  Reason: image not found```
I'm guessing this is the reason

**Comment by dem10com** [comment]
ok :) Do you have any suggestions?

**Comment by woozygoozy** [comment]
I am having the same issue - it says installed in dependency manager but in the UI it says that its not installed

**Comment by dem10com** [comment]
what is your config? ( cpu? os version ? )

**Comment by joeyballentine** [comment]
> ok :) Do you have any suggestions?

I have no idea tbh. It's missing a library file it needs. Either that means there's something you need to install or there's something I need to add to the compile process.

**Comment by dem10com** [comment]
i hust download and install python 3.9 from official site nothing change. i also try hig sierra ( 10.13.6, intel, nvidia 1080ti ) and same problem.

**Comment by joeyballentine** [comment]
No its not related to python. The ncnn package is compiled with dynamic linking, so if you are missing a library file it needs it isn't able to work.

**Comment by joeyballentine** [comment]
@dem10com are you in the chaiNNer discord and would you mind testing out the new NCNN .whl I compiled? I want to see if it resolves this issue

**Comment by dem10com** [comment]
I'm a member nowö but I'm out of town. I'll be happy to test it when I get back

**Comment by woozygoozy** [comment]
So I have tried the latest release and I can confirm that it is still not working - presenting the same issue -
![ScreenShot 2022-08-25 at 10 16@2x](https://user-images.githubusercontent.com/44062706/186689659-63f3890f-563b-4a63-98b5-09d85fa45606.jpg)
as you can see the log shows missing files...

**Comment by joeyballentine** [comment]
@woozygoozy this error is due to your computer missing vulkan. I'm not sure exactly how to resolve this but you could try installing MoltanVK through brew. If that doesn't work, then your MacBook might not support vulkan at all and therefore won't support ncnn.

**Comment by woozygoozy** [comment]
So i finally got it fixed, I downloaded vulkan SDK and then installed it via terminal

**Comment by joeyballentine** [comment]
Sweet
