### ISSUE TITLE
Multiplier for upscale node

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#807]
A combobox that specifies how many times the image should pass through the model.

**Comment by 0x4E69676874466F78** [comment]
@joeyballentine I understand. It's just less convenient.
Let's say I have a small original image (128x128) and I need to increase it to 2048x2048 (or may be 4k).

**Comment by RunDevelopment** [comment]
Sorry, but I don't think that we will add this. This is such a niche use case, that can already be done by chaining nodes today. I also want to point out that you might want to consider using a different model for 16x. Upscaling an upscaled image with the same model typically leads to quite the artifacts.

**Comment by 0x4E69676874466F78** [comment]
Okay.
