### ISSUE TITLE
Critical Error - [0.11.4] macOS 12.5.1 - Monterey 

### ISSUE THREAD

**Issue by solarpunk42** [joeyballentine/chaiNNer#825]
Got the Critical Error while launching the app.
MacOS - Monterey 12.5.1 
chaiNNer - version 0.11.4 for mac

[log.zip](https://github.com/joeyballentine/chaiNNer/files/9420357/log.zip)
<img width="1267" alt="error" src="https://user-images.githubusercontent.com/9528689/186550898-72c627b5-7747-46be-9c72-dad1f93513ff.png">
<img width="503" alt="OS" src="https://user-images.githubusercontent.com/9528689/186550923-d853dbfa-3818-44cf-b9f6-e45f5a3ec519.png">
Thanks for your help !

**Comment by joeyballentine** [comment]
Did you enable the "use system python" setting?

**Comment by solarpunk42** [comment]
Hi !
I followed this tutorial : https://www.youtube.com/watch?v=ephKzjTp6ZE
installing 3.9 as I've got Intel Processor 
[Python 3.9.13 - May 17, 2022](https://www.python.org/downloads/release/python-3913/)
Download [macOS 64-bit Intel-only installer](https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg)
I've got still the error. 
[Archive.zip](https://github.com/joeyballentine/chaiNNer/files/9420838/Archive.zip)

**Comment by joeyballentine** [comment]
Oh, I just meant it looked like it originally was working for you and something changed, so I was wondering if you changed that setting at all. Is it accurate that it was working at some point?

**Comment by joeyballentine** [comment]
I think I may have a hunch as to what's going on here, kinda. It's somehow using python 3.8, meaning you probably previously had python 3.8 installed and it is now using it. I'm guessing you did turn on the system python setting. Had you previously set up 3.8 with anaconda or something?

**Comment by solarpunk42** [comment]
The weird thing is that the first time I installed chainner it worked. But as I didn't see the node "Load Model" I added depencies in settings (Pytorch). But as I didn't see the model [Real-ESRGAN] I'm going on your discord and saw that I needed to upload the model here https://upscale.wiki/wiki/Model_Database 
But when I relaunched the app to connect the model it doesn't work at all.

**Comment by joeyballentine** [comment]
That's super strange. Do you have any idea where that python 3.8 could be coming from?

**Comment by joeyballentine** [comment]
Also, can you go to Application Support/chaiNNer/settings, open the use-system-python file in a text editor, and see if it's set to true? If it is, could you change that to false?

**Comment by solarpunk42** [comment]
wow ! 
it works fine ! Thank you Joey ! ( ˶ˆᗜˆ˵ )
a bit longer due to my old computer I guess. 
Maybe do you have advice to obtain a faster result ? 
Is it working with video ? I suppose with video frame iterator 👯  
anyway thanks ! (𓁹󠁘◡𓁹)
<img width="1253" alt="node" src="https://user-images.githubusercontent.com/9528689/186675550-d94da2a3-b1dc-414c-95a6-6f1bbd2bbb79.png">

**Comment by joeyballentine** [comment]
Unfortunately macos has to use CPU upscaling for pytorch. However, if you were to use NCNN you'd be able to upscale on your GPU which would be much faster. I'm not sure how well that works on macos, but it should theoretically work. You just need to convert the model to the ncnn format which is a bit tricky. For that you have to connect to ONNX first (there's a node for it), then you can convert to NCNN via convertmodel.com. Comverting in chainner itself will come with v0.12

As for the video iterator, that is a way to upscale video yes.  Though, it might be more reliable to export your video to frames first and use the image file iterator. Upscaling video with chaiNNer is still a bit wonky at the moment.

**Comment by solarpunk42** [comment]
Thank you ;) ! I'll experiment
Have a nice day.
