### ISSUE TITLE
Tileable textures.

### ISSUE THREAD

**Issue by ythoimust** [joeyballentine/chaiNNer#830]
So the image upscalers have tendency to not care about repeatable tiling textures. They tend to break them. Would be nice to have option to fix that tiling on the borders. It is usually done either through some smooth fading or splattering with radius in pixels. Depending on the texture one or the other method is preferable.

**Comment by joeyballentine** [comment]
We already have a way to fix this. Eventually an example will be included as a preset. Basically, use the border node to create tiling around the image (with a width of like 16 or so). Then upscale that image. Then take that result and crop the edges by the amount of the border * the scale of the model.

This is actually exactly how the seamless mode works in my esrgan fork. The difference here is you get to control the amount of border that gets created

**Comment by 0x4E69676874466F78** [comment]
@ythoimust 
![image](https://user-images.githubusercontent.com/4449851/186728915-de5c1c2d-e739-4117-af84-9fd337dadd2b.png)

**Comment by ythoimust** [comment]
Yup, worked like a charm. The only issue I see is that if I wanted to plug different size image then I had to change both values. Percentage instead of pixels would be nice addition. A problem for potential batch operations for the future I guess.
By the way nice readable interface. Rarity among small apps.

**Comment by joeyballentine** [comment]
You do not need to change the amount based on the image. It's a static amount for the width it adds around the border. And using crop edges also is a static border amount. You'd only need to change the crop amount based on the scale of the model, which you can do using the get model scale node and the math node. Then it would work for any image and any model

**Comment by ythoimust** [comment]
I understand. However lets say 16 border at certain sizes will be a problem.  64x64 vs 1024x1024 might not be the best idea to use same 16 pixels border. Again that is a problem only for batch of lets say entire textures folder.

**Comment by 0x4E69676874466F78** [comment]
Use "GET DIMENSIONS" and "MATH" nodes.

**Comment by ythoimust** [comment]
Got it, thanks.

**Comment by theflyingzamboni** [comment]
> I understand. However lets say 16 border at certain sizes will be a problem. 64x64 vs 1024x1024 might not be the best idea to use same 16 pixels border. Again that is a problem only for batch of lets say entire textures folder.

I don't know that this is the case for every model arch, but for ESRGAN at least, the pixel neighborhood is static and does not change based on image size. Because of this, the border does not need to be larger for larger images.

**Comment by joeyballentine** [comment]
Due to the way upscaling works with ESRGAN at least, you really only need a bit of a border, like 16 pixels, for any image. Doesn't matter how big. It just needs to be big enough where the inference it makes along the edges (which should normally not have the context of the tiled information on the other side of the image) has that information. Because of the way convolution work, it really only needs a little bit of a border. 16 is a very safe number.

**Comment by joeyballentine** [comment]
Going to close this since it's been resolved. Though the fact that this often gets requested shows we need to get presets done soonish
