### ISSUE TITLE
Math::Exponent/Power does not give feedback in canvas

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#837]
And `math.pow` better then `**`.

**Comment by theflyingzamboni** [comment]
Looks like exponent is just missing from the typing expression. Easy fix.

As for operators, math.pow is a lot slower than ** and always returns a float, instead of returning an int when the result is an int.

**Comment by theflyingzamboni** [comment]
Actually, maybe not as easy a fix. It looks like @RunDevelopment has not implemented a pow builtin for the type system yet.

**Comment by 0x4E69676874466F78** [comment]
@theflyingzamboni 
> math.pow is a lot slower than ** 

`timeit.timeit("7 ** i", setup="i = 5")`
0.19290430000000924 (!)
`timeit.timeit("7. ** i", setup="i = 5")`
0.12493870000002971
`timeit.timeit("7. ** i", setup="i = 5.")`
0.10786250000001019

`timeit.timeit("math.pow(7,i)", setup="import math; i = 5")`
0.14299719999996796
`timeit.timeit("math.pow(7.,i)", setup="import math; i = 5")`
0.13280789999998888
`timeit.timeit("math.pow(7.,i)", setup="import math; i = 5.")`
0.10701080000001184

**Comment by theflyingzamboni** [comment]
@0x4E69676874466F78 That's bizarre, because if you use a constant instead of a variable, ** is enormously faster.

`timeit.timeit("7 ** 5")`
0.00592789999791421

**Comment by theflyingzamboni** [comment]
@0x4E69676874466F78 ** is still going to be faster for chaiNNer in general I believe. We enforce numerical data types, so if a node requires a number with precision 0, the value will be rounded and guaranteed as an int. Since math.pow always outputs a float, the value would have to be coerced to an int even when the value is a round number, adding more than the time difference between ** and math.pow in the case of integers.

`timeit.timeit("round(5., 0)")`
0.36739409999427153
`timeit.timeit("round(5, 0)")`
0.11974499999632826

**Comment by 0x4E69676874466F78** [comment]
@theflyingzamboni i think it's cheating like precalculation/caching.
Needs to be tested in real conditions.

`timeit.timeit("7**5", number=10000)`
5.939999982729205e-05 (?)
`timeit.timeit("7**5", number=20000)`
0.0001187999996545841

`timeit.timeit("7**5", setup="import math; i=5", number=10000)`
5.959999998594867e-05
`timeit.timeit("7**5", setup="import math; i=5", number=20000)`
0.0001189000000181295

`timeit.timeit("7**i", setup="import math; i=5", number=10000)`
0.0018843999999944572
`timeit.timeit("7**i", setup="import math; i=5", number=20000)`
0.0036033000000088578

`timeit.timeit("math.pow(7,5)", setup="import math; i=5", number=10000)`
0.0014946000000009008
`timeit.timeit("math.pow(7,5)", setup="import math; i=5", number=20000)`
0.002917199999984632

`timeit.timeit("math.pow(7,i)", setup="import math; i=5", number=10000)`
0.001507099999997763
`timeit.timeit("math.pow(7,i)", setup="import math; i=5", number=20000)`
0.0028703000000120937

`timeit.timeit("math.pow(7.,i)", setup="import math; i=5.", number=10000)`
0.001049500000021908

`timeit.timeit("math.pow(7.,i)", setup="import math; i=5.", number=20000)`
0.002165999999988344

**Comment by 0x4E69676874466F78** [comment]
@theflyingzamboni okay.

**Comment by RunDevelopment** [comment]
> Actually, maybe not as easy a fix. It looks like @RunDevelopment has not implemented a pow builtin for the type system yet.

That's cause pow is non-trivial to implement for ranges of numbers (which is what types are under the hood). However, it's also not too difficult. I'll do it when I start working on chainner again.

> math.pow is a lot slower than **

That doesn't matter at all because all the executor stuff we do around it takes way longer.

**Comment by RunDevelopment** [comment]
It might be worth noting that `**` and `math.pow` do not behave the same.

```py
>>> -2 ** 2.0
-4.0
>>> -2 ** 2
-4
>>> math.pow(-2, 2)
4.0
>>> math.pow(-2, 2.0)
4.0
```

Which one is the intended behavior? We currently use `**` but given that neither @0x4E69676874466F78 nor @theflyingzamboni mentioned this difference, it might not be intentional.

For reference, JS's `Math.pow` and `**` behave like this: 
```js
> Math.pow(-2, 2) // JS doesn't have explicit float and int number types (kinda)
4
```

**Comment by joeyballentine** [comment]
I would think the behavior of ** makes more sense
