### ISSUE TITLE
An request for a download link for the integrated Python

### ISSUE THREAD

**Issue by Ravenwzj999** [joeyballentine/chaiNNer#847]
when i try to install chaiNNer, i always encounter the python error, which i can't download the integrated python through the isntaller. and it always fail, i have to try many times, reboots, uninstalls and reinstalls to overcome it.

**Comment by joeyballentine** [comment]
Did you block chaiNNer from accessing the internet?

**Comment by RunDevelopment** [comment]
@joeyballentine Can we close this? One of my recent PRs added an error message saying that internet access is required. There also hasn't been any activity on this issue.

**Comment by joeyballentine** [comment]
Sure. It's also sorta superceded by #926
