### ISSUE TITLE
How do I increment a number

### ISSUE THREAD

**Issue by db0** [joeyballentine/chaiNNer#883]
I want to rename some images in a directory into 1.jpg, 2.jpg etc.  But I can't figure how to make a number increment every iteration as I can't store variables in some way

**Comment by joeyballentine** [comment]
The index outputs in iterators are currently text (strings) not numbers, so they can't be used with the math node. This has been changed for v0.12, where now all text inputs accept numbers, and the frame indexes are now numbers. So, this will be possible in 0.12, which I plan on releasing soon.
