### ISSUE TITLE
Automatically fall back to CPU if cuda isn't available

### ISSUE THREAD

**Issue by alsa64** [joeyballentine/chaiNNer#892]
**Motivation**
While manually setting CPU mode in the settings is possible, it shouldn't be required.

**Description**
By default, if ChaiNNer doesn't detect a cuda capable GPU or if pytorch fails, try CPU processing. Really useful on platforms like macOS, where next to no cuda capable GPUs exist.

**Alternatives**
Still keep the CPU mode setting, but add an auto setting as a default instead.

**Comment by joeyballentine** [comment]
It does do this, it just doesn't for the convert to ONNX node. This is an accident.  Try to use pytorch and it will do this fine

**Comment by alsa64** [comment]
<img width="1148" alt="Screenshot 2022-09-04 at 18 35 51" src="https://user-images.githubusercontent.com/45295422/188323847-fe85ce82-ff10-4074-8df7-2c32bbfe024a.png">

**Comment by alsa64** [comment]
I never used a ONNX node, I used the new convenient pytorch -> ncnn node.

**Comment by joeyballentine** [comment]
That node internally uses the ONNX node first, which is where the issue is.
