### ISSUE TITLE
No GPU available -- but I have a GTX 3070 TI with updated drivers

### ISSUE THREAD

**Issue by jsenderatx** [joeyballentine/chaiNNer#942]
Hello! Been absolutely **loving** using chaiNNer the past few days <3

But unfortunately I cannot get chainner to recognize my GPU. I installed chainner on my wife's PC, which has a 2070 super GPU, and her GPU is recognized and works with chainner and PyTorch.

Could anyone help me figure out why my GPU is being ignored?
Below is my "System information" from chaiNNer:

{
  "app": {
    "version": "0.12.4",
    "packaged": true,
    "path": "C:\\Users\\jsend\\AppData\\Local\\chainner\\app-0.12.4\\resources\\app"
  },
  "process": {
    "cwd": "C:\\Users\\jsend\\AppData\\Local\\chainner\\app-0.12.4",
    "argv": [
      "C:\\Users\\jsend\\AppData\\Local\\chainner\\app-0.12.4\\chainner.exe"
    ]
  },
  "os": {
    "version": "Windows 10 Home",
    "release": "10.0.19044",
    "arch": "x64",
    "endianness": "LE"
  },
  "cpu": {
    "manufacturer": "",
    "brand": "",
    "vendor": "",
    "family": "",
    "model": "",
    "stepping": "",
    "revision": "",
    "voltage": "",
    "speed": null,
    "speedMin": null,
    "speedMax": null,
    "governor": "",
    "cores": 12,
    "physicalCores": 12,
    "processors": 1,
    "socket": "",
    "flags": "",
    "virtualization": false,
    "cache": {
      "l1d": 0,
      "l1i": 0,
      "l2": "",
      "l3": ""
    }
  },
  "gpus": [],
  "settings": {
    "animate-chain": "true",
    "check-upd-on-strtup": "true",
    "disable-hw-accel": "false",
    "is-cpu": "false",
    "is-fp16": "false",
    "ncnn-gpu": "0",
    "node-favorites": "[]",
    "node-selector-collapsed": "false",
    "pytorch-gpu": "0",
    "snap-to-grid": "false",
    "snap-to-grid-amount": "15",
    "startup-template": "\"\"",
    "use-dark-mode": "true",
    "use-discord-rpc": "true",
    "use-last-directory-chainner:image:file_iterator 0": "F:\\Goreyllas\\chainner batch",
    "use-last-directory-chainner:image:load 0": "C:\\Users\\jsend\\Pictures\\NFTs\\Cildhood Fantasy\\community upscale",
    "use-last-directory-chainner:image:save 1": "C:\\Users\\jsend\\Pictures\\NFTs\\Cildhood Fantasy\\community upscale",
    "use-last-directory-chainner:pytorch:load_model 0": "C:\\Users\\jsend\\Pictures\\homemade AI Art\\GANs",
    "use-last-window-size": "{\"maximized\":false,\"width\":974,\"height\":1087}",
    "use-recently-open": "[\"C:\\\\Users\\\\jsend\\\\Pictures\\\\homemade AI Art\\\\batch chain.chn\"]",
    "use-system-python": "false"
  }
}

**Comment by joeyballentine** [comment]
If you open a terminal and run the command `nvidia-smi`, what happens?

**Comment by jsenderatx** [comment]
hey thank you for the very prompt response!

I will try that, but sorry I am new to this and feeling dumb... how do I "open a terminal" to run a command?

**Comment by joeyballentine** [comment]
Press the windows button and search for "PowerShell" or "command prompt", then type in `nvidia-smi` and press enter. If it shows you GPU information then its very odd that it wouldn't work. My hunch is that it'll give you an error about not being able to find that.

**Comment by jsenderatx** [comment]
Ah thank you! And indeed you are correct -- this is what I get in response:

PS C:\Users\jsend> nvidia-smi
nvidia-smi : The term 'nvidia-smi' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nvidia-smi
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nvidia-smi:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Odd as I just reinstalled my 3080TI drivers.
Are there steps I can take to remedy this issue?

**Comment by joeyballentine** [comment]
What drivers did you install? According to Nvidia, official drivers should always contain this utility

**Comment by joeyballentine** [comment]
That's weird, I thought the studio drivers had it as well. But yeah, try installing the game ready driver and see if that fixes it.

**Comment by jsenderatx** [comment]
GameReady driver installed and still the same issue.

I did a little more digging and it seems that my nvidia-smi.exe is in the wrong location... mine is located in Windows/System32/DriverStore/FileRepository/nv_dispsig.inf_amd64

No idea why...any thoughts on how to fix this?

**Comment by 0x4E69676874466F78** [comment]
Try completely uninstalling the driver and reinstalling it in clean install mode.

![image](https://user-images.githubusercontent.com/4449851/189988632-c5350696-3c26-4e0a-92c6-5b14087ed78d.png)

**Comment by joeyballentine** [comment]
And on top of that, make sure to restart your computer after reinstalling, otherwise the evrionment variables for your system path won't be properly updated

**Comment by jsenderatx** [comment]
awesome thanks for the help.

I have uninstalled all of the NVIDIA dirvers and programs from my PC...but I still have the nvidia-smi.exe file on my computer in the System32 directory, and I am not able to delete that folder either...

Should I move forward with the reinstall of drivers? or is there something else I need to do to first scrub my PC of this nvidia-smi that is stuck in the wrong location?

**Comment by joeyballentine** [comment]
I would attempt to now install the drivers and restart your PC. If that doesn't work we can try other things, but hopefully this will force it to register than nvidia-smi exists

**Comment by jsenderatx** [comment]
Well I've done the fresh "clean" install of the drivers, restarted the PC, and unfortunately still the same issue.

Same response in PowerShell when I run nvidia-smi and no nvidia-smi.exe in my NVIDIA Corp program files path.

**Comment by joeyballentine** [comment]
You said its currently located in your system32 folder right? You could try just adding system32 to your path variable. Follow this guide: https://www.computerhope.com/issues/ch000549.htm and add the full C:/Windows/System32 path as a new entry there. Then restart your computer.

**Comment by jsenderatx** [comment]
That did the trick! Woohoo thank you so much! No way I could have figured that out on my own. Many thanks, cheers!

**Comment by joeyballentine** [comment]
Glad something finally worked :)

It's very odd because the driver installation should have done this automatically. And at the very least chaiNNer is supposed to have a backup for finding the nvidia-smi exe manually, but I guess that doesn't check System32. But yeah, doesn't really matter anymore since it's working :)

**Comment by jsenderatx** [comment]
Okay well one more concern after all... When running a chain, I have it set up to use the GPU in settings, but my CPU is still the one chugging and the newly visible VRAM meter isn't budging. Is it possible that the GPU is now recognized but still not being utilized?

**Comment by joeyballentine** [comment]
Make sure in setting > python > pytorch you have CPU set to disabled (and also turn fp16 on)

Then if that's not the problem, send your logs (help > open logs folder). It could be that cuda is failing to initialize or something

**Comment by joeyballentine** [comment]
Oh you know what, did you install pytorch while it didn't recognize your GPU? Uninstall it from the dependency manager and reinstall it, because you probably have the CPU version

**Comment by jsenderatx** [comment]
Yep indeed that worked! :D And the same job took 10% as long, awesome!
