### ISSUE TITLE
Update pytorch->ncnn node

### ISSUE THREAD

**Issue by joeyballentine** [joeyballentine/chaiNNer#945]
We have two options:
- replace with explicit pytorch->onnx->ncnn conversion
- add the outputs back in when onnx isn't there and make it error telling the user they need onnx 

I'm ok with either of these but I'm leaning toward the first

**Comment by aft** [comment]
ah, is this why i don't see save connection on convert to ncnn node?

**Comment by joeyballentine** [comment]
Yes

**Comment by aft** [comment]
i would prefer it being there and get an information message when i try to use it, if it helps.
i have been searching last 10 min on the web how to convert to ncnn using chaiNNer because the save connection wasn't there.

**Comment by joeyballentine** [comment]
That is what we are planning on changing it to. Sorry about the confusion.

**Comment by aft** [comment]
No worries. Happens. Thanks for all the hard work.
