### ISSUE TITLE
NCNN Upscale Image Node Error

### ISSUE THREAD

**Issue by trancefusiondesign** [joeyballentine/chaiNNer#946]
I'm not sure why I am receiving this error. It appears a minute after initiating.

![Screen Shot 2022-09-13 at 2 13 04 PM](https://user-images.githubusercontent.com/68971420/190010682-50035b4c-b1fe-4de7-8057-ea3d41c0e21f.png)

![Screen Shot 2022-09-13 at 2 12 09 PM](https://user-images.githubusercontent.com/68971420/190010711-77092906-4091-4fe6-917f-9975499649d3.png)

**Comment by joeyballentine** [comment]
Try using a manual number of tiles. Try 16 and then 64. One of them should work. This is a known issue with the auto tiling that I'm hoping to fix soon with an upcoming change

**Comment by trancefusiondesign** [comment]
Failed with 16 and 64. PyTorch worked last night. Maybe I should stick with it.

**Comment by joeyballentine** [comment]
How much VRAM does your GPU have?

**Comment by trancefusiondesign** [comment]
8GB

**Comment by trancefusiondesign** [comment]
AMD Radeon Pro 5500M

**Comment by trancefusiondesign** [comment]
Third time's a charm. I increased the fan speed to the max. The final output took less than five minutes!
