### ISSUE TITLE
Can't convert SwinIR pth to onnx

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [joeyballentine/chaiNNer#960]
![image](https://user-images.githubusercontent.com/4449851/190445959-6b39f48a-1da6-453c-a504-61a565aab7e2.png)

```
An error occurred in a ONNX Save Model node:

too many values to unpack (expected 2)

Input values (partial):
• Base Directory: "A:\\"
• Model Name: "003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN"
```

**Comment by Kim2091** [comment]
For now, you can use these ONNX versions that I converted. There's simplified versions too: https://mega.nz/folder/GI51QDIS#1g5hdsGLI5nVxQGoC0j0Rg

**Comment by joeyballentine** [comment]
I think I know what happened here. I bet the convert node isn't returning (session, bytes) like everything else

**Comment by joeyballentine** [comment]
Yep that's exactly what it is 

https://github.com/joeyballentine/chaiNNer/blob/13eef84b2ad7db6039cae133385ebaefc8db3f81/backend/src/nodes/pytorch_nodes.py#L466

**Comment by joeyballentine** [comment]
I'll have to do a try/except onnxruntime import here and create a session if it exists, otherwise return None as the first arg. That should fix it

**Comment by joeyballentine** [comment]
I think this might not actually be fixed. I thought it was, but now I think there is still an issue
