### ISSUE TITLE
I don't even know how I managed this… Won't even open...

### ISSUE THREAD

**Issue by hopelesscase** [joeyballentine/chaiNNer#964]
**Information:**
- Chainner version: 0.12.5
- OS: macOS 12.6

**Description**
A bunch of things broke and I admit they're probably my own doing, but I don't know what I did and don't remember all of how I got to this point. I apologize in advance for my stupidity…

First, I tried running chaiNNer, but after the macOS and Xcode update I guess they moved or deleted the command line for Xcode or something and trashed the system python? I don't know. All I know is I got alerts saying I needed to install python. I tried to see if homebrew on my system worked, but that was busted too. I fixed homebrew for my system by fixing the command line Xcode tools issue after updating it, but since there was no longer a system (I'm assuming?) python I had to figure that out next. I attempted to switch to the bundled python in chaiNNer so I trashed the Application Support folder for chaiNNer (the only way I know how to get past the error which emerges from having the system python set) and attempted to reinstall 0.12.5. Oh, the only way I got ONNX installed prior to all this was by using the system's python which is why I had it set that way. If I used the bundled python the console installing ONNX always ended with error. I figured I had it working so it was fine. I was naïve... So now I was back to trying to get ONNX running and I thought I was doing things properly, but in my confusion of the chaos around my house I ended up here with a broken chaiNNer and no idea what exactly I did to finally break it…

I'm sorry I can't seem to provide a more succinct version of events…

**Comment by joeyballentine** [comment]
You're currently running into a known issue which will be fixed by #963 -- I will release a hotfix asap

**Comment by hopelesscase** [comment]
Whew, I thought I broke it beyond repair. Thanks for letting me know. Also, thank you for all the amazing work and updates on this application. 👍
