### ISSUE TITLE
VRAM out-of memory error

### ISSUE THREAD

**Issue by Cynicalest** [joeyballentine/chaiNNer#998]
I got this error and I'm not sure how to fix it. Could someone please help me figure it out? (new to chaiNNer)
I am trying to upscale an image using Pytorch. I believe I have it set up correctly.

An error occurred in a PyTorch Upscale Image node:

A VRAM out-of-memory error has occurred. Please try using a more extreme tiling mode.

Input values (partial):
• Image: RGB image 1244x1820
• Number of Tiles: Auto

**Comment by joeyballentine** [comment]
Well, normally you shouldn't be seeing this error as the auto tiling should be taking care of it. how much VRAM does your GPU have?

**Comment by Cynicalest** [comment]
> Well, normally you shouldn't be seeing this error as the auto tiling should be taking care of it. how much VRAM does your GPU have?

I have a 5700xt graphics card that has 8gb of memory. Thanks for the quick response!

**Comment by joeyballentine** [comment]
PyTorch cannot take advantage of AMD GPUs. Did you at one point have an Nvidia GPU? it shouldn't be trying to use VRAM at all

**Comment by Cynicalest** [comment]
Oh no, I only have an AMD GPU. Or would I have to use a Nvidia GPU for PyTorch to work? or Is there another program i can use or way to fix it?

**Comment by Cynicalest** [comment]
Oh no, I only have an AMD GPU. Or would I have to use a Nvidia GPU for PyTorch to work? or Is there another program i can use or way to fix it?

**Comment by joeyballentine** [comment]
You can still use PyTorch in CPU mode. I'm just wondering if you are currently running into an issue some people experienced where previously having Nvidia drivers on your system causes it to fail trying to use CUDA. If not, then it should be using your CPU and therefore shouldn't be running into this error, meaning something else is going wrong.

The correct thing to do in your case would be to install NCNN and ONNX if you haven't already (from the dependency manager) and then convert the PyTorch models to NCNN. NCNN is able to use your AMD gpu.

**Comment by Cynicalest** [comment]
In settings, I just switched Pytorch to CPU mode and it still had the same problem. I have both NCNN and ONNX installed but I'm not sure how to convert the PyTorch models to NCNN.

**Comment by theflyingzamboni** [comment]
Use the PyTorch node called Convert to NCNN.

**Comment by Cynicalest** [comment]
Actually, i was able to figure out the conversion and got it to work! Will there be a difference in quality? I'm not exactly sure what the difference is! if someone could give a short explanation of what NCNN is I would really appreciate it. ( Newbie)

**Comment by joeyballentine** [comment]
There's no difference in quality. NCNN uses Vulkan instead of CUDA meaning it works on all modern GPUs rather than only Nvidia ones.

**Comment by Cynicalest** [comment]
> There's no difference in quality. NCNN uses Vulkan instead of CUDA meaning it works on all modern GPUs rather than only Nvidia ones.

Thank you so much! I was super excited to use this program and could not have figured it out without your help.
